# Site Settings
baseurl: ""

# Blog Setting
blog: True

# Language of the website
lang: en

# Search engine optimization settings
title: Ronghao Zhang
tagline: Undergrad at CWRU
description: Current undergraduate student at Case Western Reserve University. Studying Systems Biology and Computer Science. Originally from China.  
author: Ronghao Zhang
logo: /assets/img/rz_portrait.png
social:
  name: Ronghao Zhang 
  links:
    - https://github.com/ronghao-zhang
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Zhang
  first_name: [Ronghao, R.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
